name: Deploy to S3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: marceloluiz1/nodeapp:1.0
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "marceloluiz1/nodeapp:1.0"
        